comment:
  footer: "\
    ----\n\n
    > [!NOTE]\n
    > *This is an automated response created by a **GitHub Action***<br>
    > *Mentioning the bot won't have any effect!*
    "

labels:
  - name: 'EULA: Not accepted'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          It seems that you didn't aggre Minecraft EULA (End User License Agreement). You need to accept the terms (https://www.minecraft.net/en-us/eula) in eula.txt before running the server.
          
          This issue will be automatically closed.
        action: close
  - name: 'EULA: Not respected'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          It seems that you didn't respect the Minecraft EULA (End User License Agreement). As consequences you will not receive support.
          
          This issue will be automatically closed.
        action: close
        locking: lock
        lock_reason: EULA not respected
  - name: 'duplicate'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},

          It seems that this issue has already been reported to our contributors. If you think this is an error, please reopen the issue. Thank you for taking your time to report issue.

          This issue will be automatically closed.
        action: close
  - name: ´invalid'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          It seems that your description is not valid, or some items are missing. Please provide missing items and fill the form correctly.
    unlabeled:
      issue:
        body: |-
          Thank you for respecting the form and adding informations.
  - name: 'wontfix'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},

          This issue/request will not be done for some reasons, but we appreciate your contribution.

          This issue will be closed automatically.
        action: close