name: Comment

on:
  issues:
    types:
    - labeled
    - unlabeled
  pull_request_target:
    types:
    - labeled
    - unlabeled

jobs:
  give_comment:
    if: github.event.issue.state == 'open' || github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Send Issue/Pull request comment
      uses: peaceiris/actions-label-commenter@v1.8.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
